package TipsAndTricks.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBehaviorAspectDescriptor;
import jetbrains.mps.core.aspects.behaviour.api.BHDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public final class BehaviorAspectDescriptor extends BaseBehaviorAspectDescriptor {
  private final BHDescriptor myTT_Import__BehaviorDescriptor = new TT_Import__BehaviorDescriptor();
  private final BHDescriptor myTT_Base__BehaviorDescriptor = new TT_Base__BehaviorDescriptor();
  private final BHDescriptor myTT_Tip__BehaviorDescriptor = new TT_Tip__BehaviorDescriptor();
  private final BHDescriptor myTT_Img__BehaviorDescriptor = new TT_Img__BehaviorDescriptor();

  public BehaviorAspectDescriptor() {
  }

  @Nullable
  public BHDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    SAbstractConcept cncpt_a0h = concept;
    switch (index_846f5o_a0h.index(cncpt_a0h)) {
      case 0:
        return myTT_Base__BehaviorDescriptor;
      case 1:
        return myTT_Img__BehaviorDescriptor;
      case 2:
        return myTT_Import__BehaviorDescriptor;
      case 3:
        return myTT_Tip__BehaviorDescriptor;
      default:
    }
    return null;
  }
  private static final ConceptSwitchIndex index_846f5o_a0h = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xff3ef7856efd437aL, 0xb0d5407497433041L, 0x21ef157f5ac36f60L), MetaIdFactory.conceptId(0xff3ef7856efd437aL, 0xb0d5407497433041L, 0x21ef157f5ac37010L), MetaIdFactory.conceptId(0xff3ef7856efd437aL, 0xb0d5407497433041L, 0xf5a66eb99311abcL), MetaIdFactory.conceptId(0xff3ef7856efd437aL, 0xb0d5407497433041L, 0x21ef157f5ac36f61L)).seal();
}
