package TipsAndTricks.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_Img;
  private ConceptPresentation props_Line;
  private ConceptPresentation props_Text;
  private ConceptPresentation props_Tip;
  private ConceptPresentation props_TipsAndTricks;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.Img:
        if (props_Img == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("text");
          props_Img = cpb.create();
        }
        return props_Img;
      case LanguageConceptSwitch.Line:
        if (props_Line == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("line");
          props_Line = cpb.create();
        }
        return props_Line;
      case LanguageConceptSwitch.Text:
        if (props_Text == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("text");
          props_Text = cpb.create();
        }
        return props_Text;
      case LanguageConceptSwitch.Tip:
        if (props_Tip == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Tip = cpb.create();
        }
        return props_Tip;
      case LanguageConceptSwitch.TipsAndTricks:
        if (props_TipsAndTricks == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("TipsAndTricks");
          props_TipsAndTricks = cpb.create();
        }
        return props_TipsAndTricks;
    }
    return null;
  }
}
