package TipsAndTricks.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_TT_Base;
  private ConceptPresentation props_TT_Img;
  private ConceptPresentation props_TT_Text;
  private ConceptPresentation props_TT_Tip;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.TT_Base:
        if (props_TT_Base == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("TipsAndTricks");
          props_TT_Base = cpb.create();
        }
        return props_TT_Base;
      case LanguageConceptSwitch.TT_Img:
        if (props_TT_Img == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("img");
          props_TT_Img = cpb.create();
        }
        return props_TT_Img;
      case LanguageConceptSwitch.TT_Text:
        if (props_TT_Text == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("plain text");
          cpb.rawPresentation("text");
          props_TT_Text = cpb.create();
        }
        return props_TT_Text;
      case LanguageConceptSwitch.TT_Tip:
        if (props_TT_Tip == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_TT_Tip = cpb.create();
        }
        return props_TT_Tip;
    }
    return null;
  }
}
