package TipsAndTricks.plugin;

/*Generated by MPS */

import jetbrains.mps.make.facet.IFacet;
import org.apache.log4j.Logger;
import org.apache.log4j.LogManager;
import java.util.List;
import jetbrains.mps.make.facet.ITarget;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.make.resources.IPropertiesPersistence;
import jetbrains.mps.make.facet.ITargetEx;
import jetbrains.mps.make.script.IJob;
import jetbrains.mps.make.script.IResult;
import jetbrains.mps.make.resources.IResource;
import jetbrains.mps.make.script.IJobMonitor;
import jetbrains.mps.make.resources.IPropertiesAccessor;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.util.ProgressMonitor;
import jetbrains.mps.smodel.resources.TResource;
import jetbrains.mps.vfs.FileSystem;
import jetbrains.mps.internal.make.runtime.util.DeltaReconciler;
import jetbrains.mps.internal.make.runtime.util.FilesDelta;
import jetbrains.mps.vfs.IFile;
import java.io.File;
import com.intellij.xml.actions.xmlbeans.FileUtils;
import java.util.jar.JarOutputStream;
import java.io.IOException;
import java.io.BufferedInputStream;
import java.util.jar.JarEntry;
import java.io.FileInputStream;
import java.util.jar.Manifest;
import java.util.jar.Attributes;
import java.io.FileOutputStream;
import jetbrains.mps.baseLanguage.logging.runtime.model.LoggingRuntime;
import org.apache.log4j.Level;
import jetbrains.mps.make.script.IConfig;
import java.util.Map;
import jetbrains.mps.make.script.IPropertiesPool;

public class CreateJarResources_Facet extends IFacet.Stub {
  private static final Logger LOG = LogManager.getLogger(CreateJarResources_Facet.class);
  private List<ITarget> targets = ListSequence.fromList(new ArrayList<ITarget>());
  private IFacet.Name name = new IFacet.Name("TipsAndTricks.CreateJarResources");
  public CreateJarResources_Facet() {
    ListSequence.fromList(targets).addElement(new CreateJarResources_Facet.Target_doJar());
  }
  public Iterable<ITarget> targets() {
    return targets;
  }
  public Iterable<IFacet.Name> optional() {
    return null;
  }
  public Iterable<IFacet.Name> required() {
    return Sequence.fromArray(new IFacet.Name[]{new IFacet.Name("jetbrains.mps.lang.core.TextGen"), new IFacet.Name("jetbrains.mps.lang.core.Generate"), new IFacet.Name("TipsAndTricks.RenameXmlToHtml")});
  }
  public Iterable<IFacet.Name> extended() {
    return null;
  }
  public IFacet.Name getName() {
    return this.name;
  }
  public IPropertiesPersistence propertiesPersistence() {
    return new CreateJarResources_Facet.TargetProperties();
  }
  public static class Target_doJar implements ITargetEx {
    private static final ITarget.Name name = new ITarget.Name("TipsAndTricks.CreateJarResources.doJar");
    public Target_doJar() {
    }
    public IJob createJob() {
      return new IJob.Stub() {
        @Override
        public IResult execute(final Iterable<IResource> rawInput, final IJobMonitor monitor, final IPropertiesAccessor pa, @NotNull final ProgressMonitor progressMonitor) {
          Iterable<IResource> _output_a2vr2b_a0a = null;
          final Iterable<TResource> input = (Iterable<TResource>) (Iterable) rawInput;
          switch (0) {
            case 0:
              for (IResource resource : input) {
                final TResource tres = ((TResource) resource);
                FileSystem.getInstance().runWriteTransaction(new Runnable() {
                  public void run() {
                    new DeltaReconciler(tres.delta()).visitAll(new FilesDelta.Visitor() {
                      @Override
                      public boolean acceptWritten(IFile file) {
                        doJar(file);
                        return super.acceptWritten(file);
                      }

                      @Override
                      public boolean acceptKept(IFile file) {
                        doJar(file);
                        return super.acceptKept(file);
                      }

                      /**
                       * Trimm path to upper folder
                       */
                      private String trimmPath(String path) {
                        return path.substring(0, path.lastIndexOf("/"));
                      }


                      /**
                       * Create folders if does not exists
                       */
                      private void createFolder(File folder) {
                        if (!(folder.exists())) {
                          try {
                            folder.mkdir();
                          } catch (SecurityException s) {
                            s.printStackTrace();
                          }
                        }
                      }

                      /**
                       * Prepare structure for jarfile
                       */
                      private void createStructure(String path) {

                        File newRootFolder = new File((path + "/META-INF"));

                        createFolder(newRootFolder);

                        File source = new File(path + "/IdeTipsAndTricks.xml");
                        File dest = new File(path + "/META-INF/IdeTipsAndTricks.xml");
                        FileUtils.copyFile(source, dest);

                      }

                      /**
                       * Add file to jar
                       */
                      private void add(File source, JarOutputStream target) throws IOException {
                        BufferedInputStream in = null;

                        try {
                          if (source.isDirectory()) {
                            String name = source.getPath().replace("\\", "/");
                            if (!(name.isEmpty())) {
                              if (!(name.endsWith("/"))) {
                                name += "/";
                              }
                              JarEntry entry = new JarEntry(name);
                              entry.setTime(source.lastModified());
                              target.putNextEntry(entry);
                              target.closeEntry();
                            }
                            for (File nestedFile : source.listFiles()) {
                              add(nestedFile, target);
                            }
                            return;
                          }

                          JarEntry entry = new JarEntry("/META-INF/IdeTipsAndTricks.xml");
                          entry.setTime(source.lastModified());
                          target.putNextEntry(entry);
                          in = new BufferedInputStream(new FileInputStream(source));

                          byte[] buffer = new byte[1024];
                          while (true) {
                            int count = in.read(buffer);
                            if (count == -1) {
                              break;
                            }
                            target.write(buffer, 0, count);
                          }
                          target.closeEntry();

                        } finally {
                          if (in != null) {
                            in.close();
                          }
                        }
                      }

                      /**
                       * Add Files info new jar file
                       */
                      private void addFiles(String path) throws IOException {
                        Manifest manifest = new Manifest();
                        manifest.getMainAttributes().put(Attributes.Name.MANIFEST_VERSION, "1.0");
                        JarOutputStream target = new JarOutputStream(new FileOutputStream(path + "/ide_resources.jar"), manifest);


                        File file = new File(path + "/IdeTipsAndTricks.xml");
                        add(file, target);

                        target.close();
                      }


                      /**
                       * create Jar
                       */
                      private void doJar(final IFile file) {

                        String name = file.getName();
                        String path = trimmPath(file.getPath());


                        try {
                          addFiles(path);
                        } catch (IOException e) {
                          e.printStackTrace();
                        }

                        if (name.endsWith(".html.xml")) {
                          LoggingRuntime.logMsgView(Level.INFO, file.getPath().toString(), CreateJarResources_Facet.class, null, null);

                          // todo 
                          // add files to jar 
                          // and rename files here 
                        }

                        // navod tady 
                        // https://stackoverflow.com/questions/8522443/generate-jar-file-during-runtime 
                      }
                    });
                  }
                });
              }
            default:
              progressMonitor.done();
              return new IResult.SUCCESS(_output_a2vr2b_a0a);
          }
        }
      };
    }
    public IConfig createConfig() {
      return null;
    }
    public Iterable<ITarget.Name> notAfter() {
      return null;
    }
    public Iterable<ITarget.Name> after() {
      return Sequence.fromArray(new ITarget.Name[]{new ITarget.Name("jetbrains.mps.make.facets.Make.reconcile")});
    }
    public Iterable<ITarget.Name> notBefore() {
      return null;
    }
    public Iterable<ITarget.Name> before() {
      return Sequence.fromArray(new ITarget.Name[]{new ITarget.Name("jetbrains.mps.make.facets.Make.make")});
    }
    public ITarget.Name getName() {
      return name;
    }
    public boolean isOptional() {
      return false;
    }
    public boolean requiresInput() {
      return true;
    }
    public boolean producesOutput() {
      return true;
    }
    public Iterable<Class<? extends IResource>> expectedInput() {
      List<Class<? extends IResource>> rv = ListSequence.fromList(new ArrayList<Class<? extends IResource>>());
      ListSequence.fromList(rv).addElement(TResource.class);
      return rv;
    }
    public Iterable<Class<? extends IResource>> expectedOutput() {
      return null;
    }
    public <T> T createParameters(Class<T> cls) {
      return null;
    }
    public <T> T createParameters(Class<T> cls, T copyFrom) {
      T t = createParameters(cls);
      return t;
    }
  }
  public static class TargetProperties implements IPropertiesPersistence {
    public TargetProperties() {
    }
    public void storeValues(Map<String, String> store, IPropertiesPool properties) {
    }
    public void loadValues(Map<String, String> store, IPropertiesPool properties) {
      try {
      } catch (RuntimeException re) {
      }
    }
  }
}
